-- MySQL Script generated by MySQL Workbench
-- Sat May  3 08:34:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_user` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `locale` VARCHAR(5) NULL,
  `document` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_at` TIMESTAMP NULL,
  `address` VARCHAR(100) NULL,
  `zipcode` VARCHAR(8) NULL,
  `complement` VARCHAR(100) NULL,
  `neighborhood` VARCHAR(45) NULL,
  `city` VARCHAR(50) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(30) NULL,
  `cellphone` VARCHAR(45) NULL,
  `active` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`tb_user` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `username_UNIQUE` ON `mydb`.`tb_user` (`username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_role` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_user_roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_user_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `created_at` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_id_fk`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`tb_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `role_id_fk_idx` ON `mydb`.`tb_user_roles` (`role_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `active` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_sub_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_sub_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_sub_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `active` VARCHAR(45) NULL DEFAULT 'false',
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `category_id_fk`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`tb_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `category_id_fk_idx` ON `mydb`.`tb_sub_category` (`category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_author` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_author` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `url_photo` VARCHAR(150) NULL,
  `bio` LONGTEXT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `last_update_at` TIMESTAMP NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_book` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `published_date` DATE NOT NULL,
  `author_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `last_update_at` TIMESTAMP NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `author_id_fk`
    FOREIGN KEY (`author_id`)
    REFERENCES `mydb`.`tb_author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `author_id_fk_idx` ON `mydb`.`tb_book` (`author_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_book_sub_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_book_sub_categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_book_sub_categories` (
  `sub_category_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`sub_category_id`, `book_id`),
  CONSTRAINT `sub_category_id_fk_book`
    FOREIGN KEY (`sub_category_id`)
    REFERENCES `mydb`.`tb_sub_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id_fk_sub_category`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`tb_book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `book_id_fk_sub_category_idx` ON `mydb`.`tb_book_sub_categories` (`book_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_order` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_at` TIMESTAMP NULL,
  `totalValue` DECIMAL NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `gateway` VARCHAR(45) NOT NULL,
  `gateway_reference` VARCHAR(45) NULL,
  `merchant_reference` VARCHAR(45) NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `userId_fk_order`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `userId_fk_order_idx` ON `mydb`.`tb_order` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_item_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_item_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_item_order` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `value` DECIMAL NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  CONSTRAINT `order_id_fk_item_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`tb_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id_fk_item_order`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`tb_book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `order_id_fk_item_order_idx` ON `mydb`.`tb_item_order` (`order_id` ASC) VISIBLE;

CREATE INDEX `book_id_fk_item_order_idx` ON `mydb`.`tb_item_order` (`book_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`credit_card_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`credit_card_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`credit_card_order` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `bin_code` VARCHAR(8) NULL,
  `gateway_token` VARCHAR(80) NULL,
  `expire_date` DATE NULL,
  `card_holder_name` VARCHAR(100) NULL,
  `variant` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `order_id_fk_credit_card_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`tb_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk_credit_card_order`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `order_id_fk_credit_card_order_idx` ON `mydb`.`credit_card_order` (`order_id` ASC) VISIBLE;

CREATE INDEX `user_id_fk_credit_card_order_idx` ON `mydb`.`credit_card_order` (`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `order_id_UNIQUE` ON `mydb`.`credit_card_order` (`order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`pix_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pix_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pix_order` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `qr_code` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `order_id_fk_pix_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`tb_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk_pix_order`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `order_id_fk_pix_order_idx` ON `mydb`.`pix_order` (`order_id` ASC) VISIBLE;

CREATE INDEX `user_id_fk_pix_order_idx` ON `mydb`.`pix_order` (`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `order_id_UNIQUE` ON `mydb`.`pix_order` (`order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tb_book_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_book_details` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_book_details` (
  `id` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `summary` JSON NOT NULL,
  `number_of_pages` INT NOT NULL,
  `url_ebook` VARCHAR(150) NOT NULL,
  `book_id` INT NOT NULL,
  `url_photo` VARCHAR(150) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update_at` TIMESTAMP NULL,
  `version` INT NOT NULL,
  `published` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_fk_book_details`
    FOREIGN KEY (`book_id`)
    REFERENCES `mydb`.`tb_book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `book_id_fk_book_details_idx` ON `mydb`.`tb_book_details` (`book_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
